title: Iunia Burlan # your name (or website title) here
logo: "Iunia Burlan.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  My name is Iunia and I am currently studying for a Master's degree in Data Science at UCL (London). Prior to starting my postgraduate degree, I worked for four years as a Product Strategist within BlackRock Alternative Advisors.  
  <br><br>
  <a href="https://www.linkedin.com/in/iunia-burlan-1aa557a7/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal

